/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_casia_cripac_isee_vpe_util_VideoDecoder */

#ifndef _Included_org_casia_cripac_isee_vpe_util_VideoDecoder
#define _Included_org_casia_cripac_isee_vpe_util_VideoDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    initialize
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_initialize
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    nextFrame
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_nextFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    skipFrame
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_skipFrame
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    getChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_getChannels
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
