/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_vpe_util_Decoder */

#ifndef _Included_org_cripac_isee_vpe_util_Decoder
#define _Included_org_cripac_isee_vpe_util_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_vpe_util_Decoder
 * Method:    initialize
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_util_Decoder_initialize
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_cripac_isee_vpe_util_Decoder
 * Method:    nextFrame
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_cripac_isee_vpe_util_Decoder_nextFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_vpe_util_Decoder
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_vpe_util_Decoder_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_vpe_util_Decoder
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_util_Decoder_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_vpe_util_Decoder
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_util_Decoder_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_cripac_isee_vpe_util_Decoder
 * Method:    getChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_util_Decoder_getChannels
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
