/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_vpe_transfer_Download */

#ifndef _Included_com_vpe_transfer_Download
#define _Included_com_vpe_transfer_Download
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vpe_transfer_Download
 * Method:    decode
 * Signature: (I[B)Lcom/vpe/transfer/VideoData;
 */
JNIEXPORT jobject JNICALL Java_com_vpe_transfer_Download_decode
  (JNIEnv *, jclass, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
