/***************************************************************************
 *  This file is part of Video-Decoder.
 *
 *  Video-Decoder is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Video-Decoder is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Video-Decoder.  If not, see <http://www.gnu.org/licenses/>.
 ***************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_casia_cripac_isee_vpe_util_VideoDecoder */

#ifndef _Included_org_casia_cripac_isee_vpe_util_VideoDecoder
#define _Included_org_casia_cripac_isee_vpe_util_VideoDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    initialize
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_initialize
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    nextFrame
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_nextFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    skipFrame
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_skipFrame
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_getHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_casia_cripac_isee_vpe_util_VideoDecoder
 * Method:    getChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_casia_cripac_isee_vpe_util_VideoDecoder_getChannels
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
